// <auto-generated>
//     Generated by tools/extract_enums.py + tools/gen_enums.py from the decompiled SP LINK
//     subUpdate*Setting methods. Do not edit by hand; re-run the tools instead.
// </auto-generated>

namespace SpLink.Protocol;

public static partial class SpProConfigMap
{
    /// <summary>Value-to-label tables, keyed by converter name, exactly as SP LINK renders them.</summary>
    public static readonly IReadOnlyDictionary<string, Func<ushort, string?>> EnumLabels = new Dictionary<string, Func<ushort, string?>>
    {
        ["AccPort"] = v => v switch
        {
            0 => "External (DB9)",
            1 => "Internal (RJ45)",
            _ => null,
        },
        ["AdvancedMultiplePhasePhase"] = v => v switch
        {
            0 => "Disabled",
            1 => "L1 (0°)",
            2 => "L2 (120°)",
            3 => "L3 (240°)",
            4 => "Split (180°)",
            5 => "L1 Worker 1",
            6 => "L2 Worker 1",
            7 => "L3 Worker 1",
            8 => "Split Worker 1",
            9 => "L1 Worker 2",
            10 => "L2 Worker 2",
            11 => "L3 Worker 2",
            12 => "Split Worker 2",
            13 => "L1 Worker 3",
            14 => "L2 Worker 3",
            15 => "L3 Worker 3",
            16 => "Split Worker 3",
            _ => null,
        },
        ["AdvancedMultiplePhaseStructure"] = v => v switch
        {
            0 => "Disabled",
            1 => "Multi Single Phase",
            2 => "Two Phase (120°)",
            3 => "Three Phase",
            4 => "Three Phase + Split",
            5 => "Split Phase (180°)",
            _ => null,
        },
        ["AlarmType"] = v => v switch
        {
            0 => "Alert",
            1 => "Shutdown",
            2 => "Alert + Shutdown",
            _ => null,
        },
        ["AnalogueInputSelection"] = v => v switch
        {
            0 => "None",
            1 => "Analogue Input 1",
            2 => "Analogue Input 2",
            _ => null,
        },
        ["AppType"] = v => v switch
        {
            0 => "Off Grid",
            1 => "Mobile",
            2 => "Solar Hybrid (On Grid)",
            3 => "Solar Hybrid (AS4777.2:2020)",
            _ => null,
        },
        ["BatteryType"] = v => v switch
        {
            0 => "Lead Acid Sealed",
            1 => "Lead Acid Flooded",
            2 => "Lithium LiFePO4",
            3 => "Custom",
            4 => "BMS - LG Energy Solutions",
            5 => "BMS - BYD",
            6 => "BMS - Sonnenschein",
            7 => "BMS - RedFlow ZBM2",
            8 => "BMS - Pylontech",
            9 => "Lithium genZ",
            10 => "Lithium PowerPlus",
            11 => "BMS - Cegasa 48V",
            12 => "BMS - Cegasa/SelectCell 144V",
            13 => "BMS - Ecoult",
            14 => "BMS - Murata",
            15 => "BMS - ZYC",
            16 => "BMS - Dyness",
            17 => "BMS - Discover",
            18 => "BMS - SelectCell River Gum",
            19 => "BMS - AERL",
            20 => "BMS - XESS",
            _ => null,
        },
        ["BeepControl"] = v => v switch
        {
            0 => "Disabled",
            1 => "Enabled",
            2 => "Locked Out",
            _ => null,
        },
        ["ChargerLockout"] = v => v switch
        {
            0 => "Charging On",
            1 => "Renewable Only",
            2 => "Charging Off",
            _ => null,
        },
        ["ChargerOverrideACSourceLimit"] = v => v switch
        {
            0 => "Grid Input Limit",
            1 => "AC Source Power",
            _ => null,
        },
        ["ControlState"] = v => v switch
        {
            0 => "Follow",
            1 => "Opposite",
            _ => null,
        },
        ["DataLogInterval"] = v => v switch
        {
            1 => "1 min",
            5 => "5 min",
            10 => "10 min",
            15 => "15 min",
            30 => "30 min",
            _ => null,
        },
        ["DigitalInputSelection"] = v => v switch
        {
            0 => "None",
            1 => "Digital Control Input 1",
            2 => "Digital Control Input 2",
            3 => "Digital Control Input 3",
            4 => "Digital Control Input 4",
            5 => "Follow Backup Select",
            _ => null,
        },
        ["EdgeSelection"] = v => v switch
        {
            0 => "Rising",
            1 => "Falling",
            2 => "Both",
            _ => null,
        },
        ["ExportImport"] = v => v switch
        {
            0 => "Export",
            1 => "Import",
            _ => null,
        },
        ["Frequency"] = v => v switch
        {
            0 => "50 Hz",
            1 => "60 Hz",
            _ => null,
        },
        ["GeneratorAvailable"] = v => v switch
        {
            0 => "Assume Always",
            1 => "Follow Input",
            2 => "Follow Grid",
            _ => null,
        },
        ["GenericAcCoupling"] = v => v switch
        {
            0 => "Disabled",
            1 => "Enabled",
            2 => "Microgrid",
            _ => null,
        },
        ["LevelSelection"] = v => v switch
        {
            0 => "Active High",
            1 => "Active Low",
            _ => null,
        },
        ["ModbusPort"] = v => v switch
        {
            0 => "Disabled",
            1 => "9600 8bit Even 1stop",
            2 => "9600 8bit None 1stop",
            3 => "9600 8bit None 2stop",
            4 => "19200 8bit Even 1stop",
            5 => "19200 8bit None 1stop",
            6 => "19200 8bit None 2stop",
            7 => "57600 8bit Even 1stop",
            8 => "57600 8bit None 1stop",
            9 => "57600 8bit None 2stop",
            10 => "115200 8bit Even 1stop",
            11 => "115200 8bit None 1stop",
            12 => "115200 8bit None 2stop",
            _ => null,
        },
        ["MultiplePhase"] = v => v switch
        {
            0 => "Disabled",
            1 => "L1-Primary",
            2 => "L2-Secondary",
            3 => "L3-Secondary",
            4 => "Split Phase-Secondary",
            _ => null,
        },
        ["OutputSelection"] = v => v switch
        {
            0 => "None",
            1 => "Digital Control Output 1",
            2 => "Digital Control Output 2",
            3 => "Digital Control Output 3",
            4 => "Relay Output 1",
            5 => "Relay Output 2",
            6 => "Relay Output 3",
            7 => "Relay Output 4",
            _ => null,
        },
        ["Parallel"] = v => v switch
        {
            0 => "Disabled",
            1 => "Master",
            2 => "Slave L1",
            3 => "Slave L2",
            4 => "Slave L3",
            5 => "Slave Split Phase",
            _ => null,
        },
        ["PeriodicEqualise"] = v => v switch
        {
            0 => "Disabled",
            1 => "Charge to Equalise",
            2 => "Charge to Float",
            _ => null,
        },
        ["Port"] = v => v switch
        {
            0 => "Disabled",
            1 => "RS232 Port 1 Powador",
            2 => "RS232 Port 2 Powador",
            3 => "RS485 Port 1 Powador",
            5 => "External Comms",
            7 => "ABB / FIMER",
            9 => "SelectSun",
            10 => "Fronius SnapIN Symo",
            11 => "Fronius GEN24 Primo",
            12 => "Fronius GEN24 Symo",
            13 => "Fronius Verto",
            _ => null,
        },
        ["PowerFactorMode"] = v => v switch
        {
            0 => "Fixed AC Inverter p.f.",
            1 => "Fixed AC Source p.f.",
            2 => "Fixed Vars",
            _ => null,
        },
        ["Region"] = v => v switch
        {
            0 => " ",
            1 => "20 %",
            2 => "0 %",
            3 => "20 %",
            4 => "20 %",
            _ => null,
        },
        ["Schedule"] = v => v switch
        {
            0 => "All",
            1 => "Monday",
            2 => "Tuesday",
            3 => "Wednesday",
            4 => "Thursday",
            5 => "Friday",
            6 => "Saturday",
            7 => "Sunday",
            8 => "Monday to Friday",
            9 => "Saturday to Sunday",
            _ => null,
        },
        ["SoftBattery"] = v => v switch
        {
            0 => "Disabled",
            1 => "Softness 1",
            2 => "Softness 2",
            3 => "Softness 3",
            4 => "Softness 4",
            5 => "Softness 5",
            6 => "Softness 6",
            _ => null,
        },
        ["ThreePhaseAcSourceBalanced"] = v => v switch
        {
            0 => "Disabled",
            1 => "Balanced within 10%",
            2 => "Balanced within 5%",
            _ => null,
        },
    };
}
