import json, pathlib
m = json.load(open("tools/config_map.json"))
rows = []
for block, items in m.items():
    for it in items:
        name = it["name"].replace('"', '')
        rows.append(f'        new({block}, {it["index"]}, "{name}", "{it["converter"]}"),')
body = "\n".join(rows)
out = f'''// <auto-generated>
//     Generated by tools/extract_config_map.py + tools/gen_config_map.py from the decompiled
//     SP LINK subLoadArrayToSettings_* methods. Do not edit by hand; re-run the tools instead.
// </auto-generated>

namespace SpLink.Protocol;

public enum ConfigBlock {{ Common, AppType, BattType, Scheduler }}

/// <summary>One configuration word: where it lives, what SP LINK calls it, and how SP LINK renders it.</summary>
public readonly record struct ConfigSetting(ConfigBlock Block, int Index, string Name, string Converter);

public static partial class SpProConfigMap
{{
    private const ConfigBlock Common = ConfigBlock.Common;
    private const ConfigBlock AppType = ConfigBlock.AppType;
    private const ConfigBlock BattType = ConfigBlock.BattType;
    private const ConfigBlock Scheduler = ConfigBlock.Scheduler;

    /// <summary>All {len(rows)} configuration words recovered from SP LINK.</summary>
    public static readonly IReadOnlyList<ConfigSetting> All =
    [
{body}
    ];
}}
'''
pathlib.Path("src/SpLink.Protocol/SpProConfigMap.g.cs").write_text(out)
print(f"generated {len(rows)} settings")
