import json, pathlib
t = json.load(open("tools/config_enums.json"))
parts = []
for name, table in sorted(t.items()):
    arms = "\n".join(f'            {k} => "{v}",' for k, v in sorted(table.items(), key=lambda kv: int(kv[0])))
    parts.append(f'        ["{name}"] = v => v switch\n        {{\n{arms}\n            _ => null,\n        }},')
body = "\n".join(parts)
out = f'''// <auto-generated>
//     Generated by tools/extract_enums.py + tools/gen_enums.py from the decompiled SP LINK
//     subUpdate*Setting methods. Do not edit by hand; re-run the tools instead.
// </auto-generated>

namespace SpLink.Protocol;

public static partial class SpProConfigMap
{{
    /// <summary>Value-to-label tables, keyed by converter name, exactly as SP LINK renders them.</summary>
    public static readonly IReadOnlyDictionary<string, Func<ushort, string?>> EnumLabels = new Dictionary<string, Func<ushort, string?>>
    {{
{body}
    }};
}}
'''
pathlib.Path("src/SpLink.Protocol/SpProConfigEnums.g.cs").write_text(out)
print(f"generated {len(t)} enum tables")
