import json, pathlib
t = json.load(open("tools/event_names.json"))
parts = []
for name, table in t.items():
    arms = "\n".join(f'            [{k}] = "{v}",' for k, v in sorted(table.items(), key=lambda kv: int(kv[0])) if v)
    parts.append(f'        ["{name}"] = new Dictionary<ushort, string>\n        {{\n{arms}\n        }},')
body = "\n".join(parts)
out = f'''// <auto-generated>
//     Generated by tools/extract_event_names.py + tools/gen_event_names.py from the decompiled
//     SP LINK mDataConvert.cs. Do not edit by hand; re-run the tools instead.
// </auto-generated>

namespace SpLink.Protocol;

public static class SpProLogLabels
{{
    /// <summary>Code-to-label tables for the enumerated fields in logged records.</summary>
    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<ushort, string>> Tables =
        new Dictionary<string, IReadOnlyDictionary<ushort, string>>
    {{
{body}
    }};

    /// <summary>Returns SP LINK's label for a code, or null when the table has no entry (blank slots included).</summary>
    public static string? Lookup(string table, ushort code) =>
        Tables.TryGetValue(table, out var t) && t.TryGetValue(code, out var label) ? label : null;
}}
'''
pathlib.Path("src/SpLink.Protocol/SpProLogLabels.g.cs").write_text(out)
print(f"generated {len(t)} label tables, {sum(len(v) for v in t.values())} entries")
